# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "lucid64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"

  # Update apt-get package list on vagrant box
  config.vm.provision :shell, :inline => "apt-get update -y"

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
   config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "../../"
     chef.add_recipe "chef-janus"

     # Specify custom JSON attributes:
     chef.json = {
       :janus => {
         :users => [ "vagrant" ]
       }
     }
   end
end
